# Changes here will be overwritten by Copier
_commit: 4d84a6b
_src_path: https://github.com/python-project-templates/base.git
add_docs: true
add_extension: python
add_wiki: false
email: morissette.philippe@gmail.com
github: pmorissette
project_description: A simple and clean Sphinx theme inspired by jrnl
project_name: klink
python_version_primary: '3.11'
team: Philippe Morissette
